### ISSUE TITLE
/mystat non funziona

### ISSUE THREAD

**Issue by Kjenium** [fycarman/Prison#1]
Ho fatto sul mio server in 1.6 /mystat e mi diceva che mancavano 5mila soldi. me li sono givvati e ho rifatto il comando. diceva che mancavano ancora 5mila soldi. Ho provato a farlo quando ero al massimo rank e mi ha dato questo errore https://pastebin.com/1Ft4nFWP

**Comment by fycarman** [comment]
allega il config modificato da te.
